# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  name: Self-Hosted Agents
  demands:
    - agent.name -equals WARNI

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- script: |
    echo "Current working directory:"
    pwd
    ls -R   # Lists all files and directories to check where SimpleAPISln.sln is located
    dotnet build SimpleAPISln.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

